{
    "branch": "master",
    "verifyConditions": {                                                                                                                             
        "path": "semantic-release-docker",
        "registryUrl": "docker.io"
    },             
    "plugins": [
        "commitizen",
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [
            "@semantic-release/changelog",
            {
                "changelogFile": "CHANGELOG.md",
                "changelogTitle": "# AVEDAC Keras Image Classifier Changelog"
            }
        ],
        [
            "@semantic-release/git",
            {
                "assets": [
                    "CHANGELOG.md"
                ]
            }
        ],
        "semantic-release-docker",
        [                                                                                                                                             
            "@semantic-release/exec",                                                                                                                 
            {                                                                                                                                         
                "prepareCmd": "docker build --build-arg TF_VERSION=1.13.0rc1-gpu-py3 --build-arg DOCKER_GID=$DOCKER_GID --build-arg DOCKER_UID=$DOCKER_UID -t mbari/avedac-gpu-kclassify ."
            }
        ],                                                                                                                                            
    ],                                                                                                                                                
    "publish": [                                                                                                                                      
        {                                                                                                                                             
            "path": "semantic-release-docker",
            "name": "mbari/avedac-gpu-kclassify"
         }                                                                                                                                             
    ] 
}    